/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baithinhomv5_qllinhkien;

/**
 *
 * @author ADMIN
 */
public class DanhsachLKPanel extends javax.swing.JPanel {

    /**
     * Creates new form XoaPanel
     */
    public DanhsachLKPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbXoa_28 = new javax.swing.JLabel();
        btnXoa_28 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLK_28 = new javax.swing.JTable();

        lbXoa_28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbXoa_28.setForeground(new java.awt.Color(51, 51, 255));
        lbXoa_28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbXoa_28.setText("Danh sách linh kiện");

        btnXoa_28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Delete_20px.png"))); // NOI18N
        btnXoa_28.setText("Xóa");
        btnXoa_28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_28ActionPerformed(evt);
            }
        });

        tableLK_28.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Linh KIện", "Tên Linh KIện", "Số Lương", "Loại Linh KIện", "Giá", "Mã Sản Xuất", "Ngày nhập hàng"
            }
        ));
        jScrollPane1.setViewportView(tableLK_28);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnXoa_28, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(248, 248, 248)
                            .addComponent(lbXoa_28))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbXoa_28)
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa_28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoa_28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa_28ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnXoa_28ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXoa_28;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbXoa_28;
    private javax.swing.JTable tableLK_28;
    // End of variables declaration//GEN-END:variables
}
