/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baithinhomv5_qllinhkien;
//import User.Linhkien;
import Connection.ConnectionJDBC;
import User.Linhkien;
import User.Next1;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;
import javax.swing.table.DefaultTableModel;
//import User.Action;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
/**
 *
 * @author ADMIN
 */
public class IDT extends javax.swing.JFrame {
Next1 next;
    DefaultTableModel tbmModel;
    Linhkien linhkien;
    
    /**
     * Creates new form IDT
     */
    public IDT() {
        initComponents();
        next = new Next1();
        linhkien = new Linhkien();
        tbmModel= new DefaultTableModel(){
            @Override
                public boolean isCellEditable(int row,int column){
                    return false;
                }
        };
        jTable245.setModel(tbmModel);
        tbmModel.addColumn("Malk");
        tbmModel.addColumn("TenLK");
        tbmModel.addColumn("LoaiLK");
        tbmModel.addColumn("Gia");
        tbmModel.addColumn("SLG");
        tbmModel.addColumn("NNH");
        tbmModel.addColumn("MaSX");
        
        
        
        
        
        
        
        setTableData(next.getalllinhkiens());
        Tong();
    }
    private void setTableData(List<Linhkien> linhkiens){
        for(Linhkien linhkien: linhkiens){
            tbmModel.addRow(new Object[]{linhkien.getMaLK(), linhkien.getTenLK(),linhkien.getLoaiLK(),linhkien.getGia(),linhkien.getSLG(),linhkien.getNNH(),linhkien.getMaSX()});
        }
     
    
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back245 = new javax.swing.JButton();
        IN245 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable245 = new javax.swing.JTable();
        Show245 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Start245 = new javax.swing.JTextField();
        Endlabel245 = new javax.swing.JLabel();
        jLabelstart245 = new javax.swing.JLabel();
        End245 = new javax.swing.JTextField();
        JlabelTong245 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back245.setText("Hệ thống");
        Back245.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back245ActionPerformed(evt);
            }
        });

        IN245.setText("In thống kê");
        IN245.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IN245ActionPerformed(evt);
            }
        });

        jTable245.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable245);

        Show245.setText("Xem Thống kê");
        Show245.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show245ActionPerformed(evt);
            }
        });

        Endlabel245.setText("Đến ngày :");

        jLabelstart245.setText("Thống kê từ ngày :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelstart245, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Endlabel245, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Start245, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(End245, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelstart245, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Start245, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Endlabel245, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(End245, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        JlabelTong245.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Show245, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(IN245, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Back245, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlabelTong245, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Back245, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Show245, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IN245, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(JlabelTong245, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IN245ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IN245ActionPerformed
        // TODO add your handling code here:
        BaoCao bc= new BaoCao(Start245.getText(), End245.getText());
        bc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_IN245ActionPerformed

    private void Show245ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show245ActionPerformed
        Statement st = null;
        ResultSet rs = null;
        String Date1=Start245.getText();
        String Date2=End245.getText();
        Connection connection=ConnectionJDBC.getJDBCConnection();
        try {
            // Câu lệnh xem dữ liệu
            String sql = "select * from LinhKien  ";
            
            // Nếu tìm kiếm theo title
            if (Start245.getText().length() > 0) 
                if(End245.getText().length()>0)
                    sql = sql + " where NNH BETWEEN '" + Date1 + " 00:00:00' AND '" + Date2 + " 23:59:59  '";
                

            // Tạo đối tượng thực thi câu lệnh Select
            st = connection.createStatement();

            // Thực thi 
            rs = st.executeQuery(sql);
            Vector data = null;

            tbmModel.setRowCount(0);

            // Nếu sách không tồn tại
            if (rs.isBeforeFirst() == false) {
                JOptionPane.showMessageDialog(this, "Không có đơn hàng trong ngày này");
                return;
            }

            // Trong khi chưa hết dữ liệu
            while (rs.next()) {
                data = new Vector();
                data.add(rs.getString("MaLK"));
                data.add(rs.getString("TenLK"));
                data.add(rs.getString("LLK"));
                data.add(rs.getString("Gia"));
                data.add(rs.getInt("SLG"));
                data.add(rs.getDate("NNH"));
                
                data.add(rs.getString("MaSX"));
                
                
                
               
                // Thêm một dòng vào table model
                tbmModel.addRow(data);
            }

            jTable245.setModel(tbmModel); // Thêm dữ liệu vào table
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (connection != null) {
                    connection.close();
                }
                if (st != null) {
                    st.close();
                }
                if (rs != null) {
                    rs.close();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        Tong();                                 

    }//GEN-LAST:event_Show245ActionPerformed

    private void Back245ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back245ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Quanlylinhkien_nhanvien().setVisible(true);
    }//GEN-LAST:event_Back245ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back245;
    private javax.swing.JTextField End245;
    private javax.swing.JLabel Endlabel245;
    private javax.swing.JButton IN245;
    private javax.swing.JLabel JlabelTong245;
    private javax.swing.JButton Show245;
    private javax.swing.JTextField Start245;
    private javax.swing.JLabel jLabelstart245;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable245;
    // End of variables declaration//GEN-END:variables

    
    private void Tong(){
        DecimalFormat x= new DecimalFormat("###,###,###");
        int Tong=0;
        for(int i=0;i<jTable245.getRowCount();i++){
            Tong+=Integer.parseInt(jTable245.getValueAt(i, 3).toString());
        }
        JlabelTong245.setText("Tổng doanh thu :"+ x.format(Tong)+" "+"VND");
    }

}
