/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baithinhomv5_qllinhkien;

/**
 *
 * @author ADMIN
 */
public class QuanlyLK extends javax.swing.JFrame {
    private SuaPanel mSua;
    private ThemPanel mThem;
    private DanhsachLKPanel mXoa;
    /**
     * Creates new form Quanlynv
     */
    public QuanlyLK() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbQuanliLK_237 = new javax.swing.JLabel();
        btnThem_237 = new javax.swing.JButton();
        btnSua_237 = new javax.swing.JButton();
        btndslk_237 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panelView_237 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbQuanliLK_237.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbQuanliLK_237.setForeground(new java.awt.Color(255, 51, 102));
        lbQuanliLK_237.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuanliLK_237.setText("Quản Lý Linh KIện");

        btnThem_237.setBackground(new java.awt.Color(102, 255, 255));
        btnThem_237.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem_237.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_20px.png"))); // NOI18N
        btnThem_237.setText("Thêm Linh Kiện");
        btnThem_237.setMaximumSize(new java.awt.Dimension(62, 23));
        btnThem_237.setMinimumSize(new java.awt.Dimension(72, 23));
        btnThem_237.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_237ActionPerformed(evt);
            }
        });

        btnSua_237.setBackground(new java.awt.Color(102, 255, 255));
        btnSua_237.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua_237.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_computer_support_20px.png"))); // NOI18N
        btnSua_237.setText("Sửa Linh Kiện");
        btnSua_237.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua_237ActionPerformed(evt);
            }
        });

        btndslk_237.setBackground(new java.awt.Color(102, 255, 255));
        btndslk_237.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndslk_237.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_workspace_20px.png"))); // NOI18N
        btndslk_237.setText("Danh sách linh kiện");
        btndslk_237.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndslk_237ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_cancel_20px.png"))); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbQuanliLK_237, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndslk_237, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua_237, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem_237, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(panelView_237, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelView_237)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbQuanliLK_237, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndslk_237, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSua_237, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThem_237, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThem_237ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_237ActionPerformed
        // TODO add your handling code here:
        if(mThem == null){
            mThem =new ThemPanel();
            panelView_237.addTab("Thêm Nhân Viên", mThem);
        }
        panelView_237.setSelectedComponent(mThem);
    }//GEN-LAST:event_btnThem_237ActionPerformed

    private void btnSua_237ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua_237ActionPerformed
        // TODO add your handling code here:
        if(mSua == null){
            mSua =new SuaPanel();
            panelView_237.addTab("Sửa Nhân Viên", mSua);
        }
        panelView_237.setSelectedComponent(mSua);

    }//GEN-LAST:event_btnSua_237ActionPerformed

    private void btndslk_237ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndslk_237ActionPerformed
        // TODO add your handling code here:
        if(mXoa == null){
            mXoa =new DanhsachLKPanel();
            panelView_237.addTab("Xóa Nhân Viên", mXoa);
        }
        panelView_237.setSelectedComponent(mXoa);
    }//GEN-LAST:event_btndslk_237ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanlyLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanlyLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanlyLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanlyLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanlyLK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua_237;
    private javax.swing.JButton btnThem_237;
    private javax.swing.JButton btndslk_237;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbQuanliLK_237;
    private javax.swing.JTabbedPane panelView_237;
    // End of variables declaration//GEN-END:variables
}
