/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baithinhomv5_qllinhkien;

/**
 *
 * @author ADMIN
 */
public class SuaLKPanel extends javax.swing.JPanel {

    /**
     * Creates new form SuaPanel
     */
    public SuaLKPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTieude_237 = new javax.swing.JLabel();
        btnCapnhat237 = new javax.swing.JButton();
        txtsoLuong_237 = new javax.swing.JTextField();
        lbsoLuong_237 = new javax.swing.JLabel();
        lbSdt_28 = new javax.swing.JLabel();
        txtMSX_237 = new javax.swing.JTextField();
        txtGia_237 = new javax.swing.JTextField();
        txtTenLK_237 = new javax.swing.JTextField();
        lbTenNV_28 = new javax.swing.JLabel();
        lbGia = new javax.swing.JLabel();
        cbloailk_237 = new javax.swing.JComboBox<>();
        lbllk_237 = new javax.swing.JLabel();
        lbManhanvien_28 = new javax.swing.JLabel();
        jCBmalk_237 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtngay_237 = new javax.swing.JTextField();

        lbTieude_237.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTieude_237.setForeground(new java.awt.Color(255, 51, 102));
        lbTieude_237.setText("Cập Nhật Linh Kiện");

        btnCapnhat237.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_computer_support_20px.png"))); // NOI18N
        btnCapnhat237.setText("Cập Nhật");

        lbsoLuong_237.setText("Số Lương:");

        lbSdt_28.setText("Mã nhà sx:");

        txtGia_237.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGia_237ActionPerformed(evt);
            }
        });

        txtTenLK_237.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenLK_237ActionPerformed(evt);
            }
        });

        lbTenNV_28.setText("Tên Linh kiện:");

        lbGia.setText("Giá:");

        cbloailk_237.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbllk_237.setText("Loại linh kiện:");

        lbManhanvien_28.setText("Mã Linh Kiện:");

        jCBmalk_237.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Ngày Nhập Hàng:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lbManhanvien_28)
                                .addGap(25, 25, 25)
                                .addComponent(jCBmalk_237, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(lbllk_237))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtngay_237, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(cbloailk_237, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTenNV_28)
                            .addComponent(lbGia))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTenLK_237, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGia_237, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbsoLuong_237, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSdt_28, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMSX_237)
                            .addComponent(txtsoLuong_237, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(btnCapnhat237, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(lbTieude_237)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbTieude_237)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lbManhanvien_28))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtsoLuong_237, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbsoLuong_237)
                                .addComponent(txtTenLK_237, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbTenNV_28)))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbllk_237)
                                        .addComponent(cbloailk_237, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lbSdt_28)
                                                .addComponent(txtGia_237, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtMSX_237, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtngay_237, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbGia))
                        .addGap(4, 4, 4)
                        .addComponent(btnCapnhat237, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jCBmalk_237, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenLK_237ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenLK_237ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenLK_237ActionPerformed

    private void txtGia_237ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGia_237ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGia_237ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat237;
    private javax.swing.JComboBox<String> cbloailk_237;
    private javax.swing.JComboBox<String> jCBmalk_237;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbGia;
    private javax.swing.JLabel lbManhanvien_28;
    private javax.swing.JLabel lbSdt_28;
    private javax.swing.JLabel lbTenNV_28;
    private javax.swing.JLabel lbTieude_237;
    private javax.swing.JLabel lbllk_237;
    private javax.swing.JLabel lbsoLuong_237;
    private javax.swing.JTextField txtGia_237;
    private javax.swing.JTextField txtMSX_237;
    private javax.swing.JTextField txtTenLK_237;
    private javax.swing.JTextField txtngay_237;
    private javax.swing.JTextField txtsoLuong_237;
    // End of variables declaration//GEN-END:variables
}
