/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JAVA_CuoiKi;

/**
 *
 * @author ADMIN
 */
public class SuaPanel extends javax.swing.JPanel {

    /**
     * Creates new form SuaPanel
     */
    public SuaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTieude_28 = new javax.swing.JLabel();
        txtLuong_28 = new javax.swing.JTextField();
        lbLuong_28 = new javax.swing.JLabel();
        txtSdt_28 = new javax.swing.JTextField();
        lbSdt_28 = new javax.swing.JLabel();
        txtEmail_28 = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();
        lbTenNV_28 = new javax.swing.JLabel();
        txtTenNV_28 = new javax.swing.JTextField();
        rdbNu_28 = new javax.swing.JRadioButton();
        rdbNam_28 = new javax.swing.JRadioButton();
        txtMaNV_28 = new javax.swing.JTextField();
        lbManhanvien_28 = new javax.swing.JLabel();
        lbGioitinh_28 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNV_28 = new javax.swing.JTable();
        btnCapnhat28 = new javax.swing.JButton();

        lbTieude_28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTieude_28.setForeground(new java.awt.Color(255, 51, 102));
        lbTieude_28.setText("Cập Nhật Nhân Viên");

        lbLuong_28.setText("Lương:");

        lbSdt_28.setText("SĐT:");

        lbEmail.setText("Email:");

        lbTenNV_28.setText("Tên Nhân Viên:");

        rdbNu_28.setText("Nữ");

        rdbNam_28.setText("Nam");

        lbManhanvien_28.setText("Mã Nhân Viên:");

        lbGioitinh_28.setText("Giới tính:");

        tableNV_28.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Lương", "Giới Tính", "Email", "SĐT"
            }
        ));
        jScrollPane1.setViewportView(tableNV_28);

        btnCapnhat28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_upgrade_40px.png"))); // NOI18N
        btnCapnhat28.setText("Cập Nhật");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbManhanvien_28)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaNV_28, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbTenNV_28)
                        .addGap(10, 10, 10)
                        .addComponent(txtTenNV_28, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(lbLuong_28)
                        .addGap(18, 18, 18)
                        .addComponent(txtLuong_28, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCapnhat28, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbGioitinh_28)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdbNam_28)
                                        .addGap(32, 32, 32)
                                        .addComponent(rdbNu_28)
                                        .addGap(43, 43, 43)
                                        .addComponent(lbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtEmail_28, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(59, 59, 59)
                                .addComponent(lbSdt_28)
                                .addGap(18, 18, 18)
                                .addComponent(txtSdt_28, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(lbTieude_28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbTieude_28)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaNV_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbManhanvien_28)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbTenNV_28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtTenNV_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLuong_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLuong_28)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbNam_28)
                        .addComponent(lbGioitinh_28)
                        .addComponent(rdbNu_28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtEmail_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbSdt_28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtSdt_28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(btnCapnhat28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat28;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbGioitinh_28;
    private javax.swing.JLabel lbLuong_28;
    private javax.swing.JLabel lbManhanvien_28;
    private javax.swing.JLabel lbSdt_28;
    private javax.swing.JLabel lbTenNV_28;
    private javax.swing.JLabel lbTieude_28;
    private javax.swing.JRadioButton rdbNam_28;
    private javax.swing.JRadioButton rdbNu_28;
    private javax.swing.JTable tableNV_28;
    private javax.swing.JTextField txtEmail_28;
    private javax.swing.JTextField txtLuong_28;
    private javax.swing.JTextField txtMaNV_28;
    private javax.swing.JTextField txtSdt_28;
    private javax.swing.JTextField txtTenNV_28;
    // End of variables declaration//GEN-END:variables
}
